version: '3.8'
services:
    redis:
      image: redis:latest
      ports:
        # TODO: Parse env var and extract out port from it
        - 6379
      container_name: redis-container
    
    web:
      build: .
      environment: 
        PROXY_ADDRESS: ${PROXY_ADDRESS}
        FLASK_DEBUG: 1
        PYTHONUNBUFFERED: 1
        CACHE_GLOBAL_EXPIRY: ${CACHE_GLOBAL_EXPIRY}
        CACHE_CAPACITY: ${CACHE_CAPACITY}
        BACKING_REDIS_ADDRESS: ${BACKING_REDIS_ADDRESS}
        MAX_CLIENTS: ${MAX_CLIENTS}
        MAX_REQUESTS: ${MAX_REQUESTS}
      ports:
        - "8080:5000"
      container_name: flask-container