FROM python:latest

# Environment variables
ENV PROXY_PORT ${PROXY_PORT_TCP}

WORKDIR /usr/assignment/tcp_server

COPY ./tcp_server/requirements.txt /usr/assignment/tcp_server/requirements.txt
RUN pip3 install -r requirements.txt

ADD ./tcp_server /usr/assignment/tcp_server
ADD ./package /usr/assignment/tcp_server/package

ADD ./package/cache/tests /usr/assignment/tcp_server/tests/test_cache
ADD ./tcp_server/tests /usr/assignment/tcp_server/tests/test_tcp_server

EXPOSE ${PROXY_PORT}