version: '3.8'
services:
    redis:
      image: redis:latest
      container_name: redis-container

    web:
      build:
        context: .
        dockerfile: dockerfile_web
      environment: 
        PROXY_HOST: ${PROXY_HOST}
        PROXY_PORT: ${PROXY_PORT}
        FLASK_DEBUG: 1
        PYTHONUNBUFFERED: 1
        CACHE_GLOBAL_EXPIRY: ${CACHE_GLOBAL_EXPIRY}
        CACHE_CAPACITY: ${CACHE_CAPACITY}
        BACKING_REDIS_HOST: ${BACKING_REDIS_HOST}
        BACKING_REDIS_PORT: ${BACKING_REDIS_PORT}
        MAX_CLIENTS: ${MAX_CLIENTS}
        MAX_REQUESTS: ${MAX_REQUESTS}
      ports:
        - "8080:${PROXY_PORT}"
      restart: always
      container_name: flask-container
    
    tcp_server:
      build:
        context: .
        dockerfile: dockerfile_tcp_server
      command: python ./server.py
      environment:
        PROXY_HOST: ${PROXY_HOST_TCP}
        PROXY_PORT: ${PROXY_PORT_TCP}
        PYTHONUNBUFFERED: 1
        CACHE_GLOBAL_EXPIRY: ${CACHE_GLOBAL_EXPIRY}
        CACHE_CAPACITY: ${CACHE_CAPACITY}
        BACKING_REDIS_HOST: ${BACKING_REDIS_HOST}
        BACKING_REDIS_PORT: ${BACKING_REDIS_PORT}
        MAX_CLIENTS: ${MAX_CLIENTS}
        MAX_REQUESTS: ${MAX_REQUESTS}
      ports:
        - "${LOCAL_PORT_TCP}:${PROXY_PORT_TCP}"
      restart: always
      container_name: tcp-server-container