version: '3.8'
services:
    redis:
      image: redis:latest
      ports:
        - 6379
      container_name: redis-container
    
    web:
      build: .
      environment: 
        PORT: 5000
        HOST: 0.0.0.0
        FLASK_DEBUG: 1
      ports:
        - "8080:5000"
      container_name: flask-container