version: '3'
services:
    redis:
      image: redis:latest
      ports:
        - 6379
      container_name: redis-container
    
    web:
      build: .
      ports:
        - "8080:5000"
      container_name: flask-container